# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "year_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
md5 = "0.7.0"